# Compose file for a Alastria-B node

version: "3.7"

services:
    alastria-node:
        build: ./alastria-node
        container_name: ${NODE_NAME}
        volumes:
            - /data/alastria-node-besu/database:/data/alastria-node-besu/database
            - /data/alastria-node-besu/logs:/data/alastria-node-besu/logs
            - keys:/data/alastria-node-besu/keys
        ports:
            - "30303:30303/tcp"
            - "30303:30303/udp"
            - "9545:9545/tcp"
            # Orion port (in case you use private transactions)
            # - "8080:8080/tcp"
            #
            # json+rpc (in case you use remix/truffle/.../web3)
            # - "8545:8545/tcp"
            #
            # json+ws (in case you use remix/truffle/.../web3)
            # - "8546:8546/tcp"
        environment:
            - LOG4J_CONFIGURATION_FILE=/data/alastria-node-besu/config/log-config.xml
            - NODE_TYPE=${NODE_TYPE}
            - NODE_BRANCH=${NODE_BRANCH}
            
volumes:
    keys:
